server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ruijiwaimai?characterEncoding=utf-8?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
#      redis6之后才有username
  redis:
    database: 0
    host: 192.168.142.128
    port: 6379
    password: root
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
ruijiwaimai:
  path: C:\Users\36017\Desktop\java\picture\ppp\
